# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6c25bafb2a8f12450f822b638d1172a0faa278af9698d58456f55013a120a1f46e91ffa2535129a406d891d71b48e0ee5d8f2a673ce5395ed2b813cc8e9496a

test:
  secret_key_base: ba24acadf859f501ab14709d75cd7a318391bca764e1d620421290aafaced1c60d7285b63ecefcac45ff98922873118ababfdef704b8b0ec4c79be074c3f2e1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
